### ISSUE TITLE
website 

### ISSUE THREAD

**Issue by logan-wrld** [Leto-gg/website#3]
leto.gg

**Comment by logan-wrld** [comment]
[website link](https://s3.amazonaws.com/leto.gg/index.html)

**Comment by galaxyxtwo** [comment]
This link works. But when I search leto.gg, the bucket/site cannot be reached.

**Comment by logan-wrld** [comment]
I believe our Cloudflare route is getting in the way- going to fix this now

**Comment by logan-wrld** [comment]
It seems as if the NS records were not correct within the Registered Domains Section in Route 53... The other records on the main routing table are all correct... After checking NSLookup, you could see everything was still pointing to CF. I fixed the records and now we wait to make sure everything's is good!

**Comment by logan-wrld** [comment]
Maybe reset the whole CF configuration. Once DNS name servers are updated, that is when everything becomes unresponsive...

**Comment by logan-wrld** [comment]
FInally figured out how to remove site from Cloudflare... At the bottom of the "Overview" page, there is THE button. Reset this configuration- That should fix the SSL problem!
![Screenshot 2023-02-11 at 1 39 24 AM](https://user-images.githubusercontent.com/30084404/218246743-0da933ea-429f-4562-887d-2fccd24797ce.png)

**Comment by logan-wrld** [comment]
Switched DNS records back to Cloudflare after removing the site like what is illustrated above. Now that the DNS records are changed, we need to wait. In general, you can expect most changes to propagate within a few hours, but it's always a good idea to wait 24 hours to ensure that all DNS servers have received the updates.

**Comment by logan-wrld** [comment]
This is fixed, Leto.gg dns was fixed by deleting the site from Cloudflare, then , the domain was able to be resolved and then I added the CF name server addresses to Route53 and boom, success
